In [1]:
import numpy as np
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])
C = A + B
D = A - B
E = A * B
F = np.dot(A,B)# orA@B
A_transpose=A.T
print("Addition:")
print(C)
print("\nSubstraction:")
print(D)
print("\nElement-Wise Multiplication:")
print(E)
print("\nMatrix Multiplication:")
print(F)
print("\n Transpose:")
print(A_transpose)

Addition:
[[ 6  8]
 [10 12]]

Substraction:
[[-4 -4]
 [-4 -4]]

Element-Wise Multiplication:
[[ 5 12]
 [21 32]]

Matrix Multiplication:
[[19 22]
 [43 50]]

 Transpose:
[[1 3]
 [2 4]]
